"""initial gtm schema

Revision ID: b61917a8b603
Revises: 
Create Date: 2026-09-24 08:53:22.081441
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = 'b61917a8b603'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('cycle_count', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('search_provider', sa.String(length=40), nullable=False),
    sa.Column('laya_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laya_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('decision_mode', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('probabilities_json', sa.Text(), nullable=False),
    sa.Column('checkpoint_trained_for_redis_gtm', sa.Boolean(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('published_at', sa.String(length=20), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.Column('poisoned', sa.Boolean(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('use_case_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('relevance', sa.String(length=40), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('falsifier', sa.Text(), nullable=False),
    sa.Column('alternatives_json', sa.Text(), nullable=False),
    sa.Column('unknowns_json', sa.Text(), nullable=False),
    sa.Column('supporting_evidence_ids_json', sa.Text(), nullable=False),
    sa.Column('contradicting_evidence_ids_json', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owning_functions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('function_id', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_ids_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('identity_confidence', sa.Float(), nullable=False),
    sa.Column('persona_id', sa.String(length=80), nullable=True),
    sa.Column('seniority', sa.Float(), nullable=False),
    sa.Column('role_relevance', sa.Float(), nullable=False),
    sa.Column('problem_ownership', sa.Float(), nullable=False),
    sa.Column('technical_relevance', sa.Float(), nullable=False),
    sa.Column('timing_relevance', sa.Float(), nullable=False),
    sa.Column('public_evidence', sa.Float(), nullable=False),
    sa.Column('contact_confidence', sa.Float(), nullable=False),
    sa.Column('dossier_json', sa.Text(), nullable=False),
    sa.Column('source_urls_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('person_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('why_this_person', sa.Text(), nullable=False),
    sa.Column('technical_signal', sa.Text(), nullable=False),
    sa.Column('why_now', sa.Text(), nullable=False),
    sa.Column('redis_hypothesis', sa.Text(), nullable=False),
    sa.Column('unknowns_json', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=True),
    sa.Column('template_id', sa.String(length=80), nullable=True),
    sa.Column('draft', sa.Text(), nullable=True),
    sa.Column('confidence_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=False),
    sa.Column('brief_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('node', sa.String(length=80), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('signal_type', sa.String(length=80), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ids_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('why_now',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('event_date', sa.String(length=20), nullable=True),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('evidence_ids_json', sa.Text(), nullable=False),
    sa.Column('buying_intent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=True),
    sa.Column('template_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('draft', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('published_at', sa.String(length=20), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('lineage_json', sa.Text(), nullable=False),
    sa.Column('topics_json', sa.Text(), nullable=False),
    sa.Column('supports_problem', sa.Boolean(), nullable=False),
    sa.Column('contradicts_redis', sa.Boolean(), nullable=False),
    sa.Column('is_explicit_gap', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('ranking_updated', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcomes')
    op.drop_table('evidence')
    op.drop_table('actions')
    op.drop_table('why_now')
    op.drop_table('signals')
    op.drop_table('research_log')
    op.drop_table('recommendations')
    op.drop_table('people')
    op.drop_table('owning_functions')
    op.drop_table('opportunities')
    op.drop_table('observations')
    op.drop_table('laya_decisions')
    op.drop_table('research_runs')
    op.drop_table('accounts')
    # ### end Alembic commands ###
